name: Deploy to Production

on:
  push:
    branches:
      - without_filament_institution

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, bcmath, zip
          
      - name: Setup Volta
        uses: volta-cli/action@v4
          
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.REMOTE_DIR }}
            git pull origin without_filament_institution
            sudo -u www-data composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
            sudo -u www-data npm ci
            sudo -u www-data npm run build
            sudo -u www-data php artisan config:cache
            sudo -u www-data php artisan route:cache
            sudo -u www-data php artisan view:cache
            sudo -u www-data php artisan optimize:clear
            sudo -u www-data php artisan optimize
            sudo chown -R www-data:www-data storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache
            sudo systemctl restart apache2