name: Deploy to Production

on:
  push:
    branches:
      - without_filament_institution

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, bcmath, zip
          
      - name: Setup Volta
        uses: volta-cli/action@v4
          
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to EC2
        env:
          SSHPASS: ${{ secrets.SSHPASS }}
        run: |
          # Use sshpass to connect to EC2 and execute commands
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} <<'EOF'
          
          # Ensure correct permissions for the project directory
          sudo chown -R www-data:www-data ${{ secrets.REMOTE_DIR }}
          sudo chmod -R 755 ${{ secrets.REMOTE_DIR }}
          cd ${{ secrets.REMOTE_DIR }}
          
          # Pull the latest code
          sudo git pull origin without_filament_institution
          
          # Install dependencies and build
          sudo -u www-data composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
          sudo -u www-data npm ci
          sudo -u www-data npm run build
          
          # Clear and cache Laravel configurations
          sudo -u www-data php artisan config:clear
          sudo -u www-data php artisan config:cache
          sudo -u www-data php artisan route:cache
          sudo -u www-data php artisan view:cache
          sudo -u www-data php artisan optimize:clear
          sudo -u www-data php artisan optimize
          
          # Set correct permissions for storage and cache
          sudo chown -R www-data:www-data ${{ secrets.REMOTE_DIR }}/storage ${{ secrets.REMOTE_DIR }}/bootstrap/cache
          sudo chmod -R 775 ${{ secrets.REMOTE_DIR }}/storage ${{ secrets.REMOTE_DIR }}/bootstrap/cache
          
          # Restart Apache
          sudo systemctl restart apache2
          
          EOF